# -*- coding:utf-8 -*-
"""
    默认数据
# author: albert
# date: 2020/12/25
# update: 2020/12/25
"""


DEFAULT_PLATFORM_FIELDS = {
    "status": 1,
    "name": "",
    "introduction": "",
    "logo": "",
    "weMediaName": "",       # 该平台的自媒体账号统称，参考：【公众号】、【微博】、【头条号】、【抖音号】、【快手号】、【人民号】、【大风号】、【大鱼号】、【企鹅号】、【网易号】、【百家号】等
    "url": "",
    "type": 0,               # 平台类型，1微信、2微博、3网站、4APP、5电子报、6论坛、7自媒体
    "types": [],
    "sourceTypes": [],
    "selfTypesIDs": [],
    "region": [],
    "worksNum": 0,
    "extendData": "",
    "createTime": 0,
    "updateTime": 0,
    "latestWorksTime": 0,
}


DEFAULT_USER_INFO_FIELDS = {
    "status": 1,
    "platformAccountID": "",          # 12.28添加
    "name": "",
    "avatar": "",
    "qrcode": "",
    "gender": -1,                    # 性别，-1未知，1男，2女，3其它
    "mobilePhoneNumber": "",
    "email": "",
    "identityCode": "",
    "certificationType": -1,
    "url": "",
    "region": [],
    "types": [],                     # 分类ID列表（某种含义上的父节点ID列表）
    "selfTypesIDs": [],              # 自己的分类ID列表
    "platformID": "",
    "platformName": "",
    "platformWorksNum": 0,
    "platformFansNum": 0,
    "platformFollowsNum": 0,
    "platformReadsNum": 0,
    "platformLikesNum": 0,
    "platformCommentsNum": 0,
    "platformForwardsNum": 0,
    "worksNum": 0,
    "readNum": 0,
    "likeNum": 0,
    "commentNum": 0,
    "forwardNum": 0,
    "collectNum": 0,
    "createTime": 0,
    "updateTime": 0,
    "platformType": 0,              # 【信源平台】索引中的【type】，1微信、2微博、3网站、4APP、5电子报、6论坛、7自媒体
    "weMediaName": "",              # 该平台的自媒体账号统称，参考：【公众号】、【微博】、【头条号】、【抖音号】、【快手号】、【人民号】、【大风号】、【大鱼号】、【企鹅号】、【网易号】、【百家号】等
}


DEFAULT_WORKS_FIELDS = {
    "status": 1,
    "platformWorksID": "",          # 12.28添加
    "platformID": "",
    "platformName": "",
    "platformType": -1,             #【信源平台】索引中的【type】，1微信、2微博、3网站、4APP、5电子报、6论坛、7自媒体
    "channelID": "",
    "channelName": "",
    "accountID": "",
    "accountName": "",
    "topicID": "",
    "topicTitle": "",
    "epaperLayoutID": "",
    "url": "",
    "authors": [],
    "editors": [],
    "hbrbAuthors": [],
    "preTitle": "",
    "subTitle": "",
    "title": "",
    "titleWordsNum": 0,
    "content": "",
    "contentWordsNum": 0,
    "html": "",
    "simhash": "",
    "contentType": -1,
    "digest": "",
    "digestOriginal": "",
    "digestCompute": "",
    "source": "",
    "isOriginal": -1,
    "isOriginalCompute": -1,
    "isTop": -1,
    "isPush": -1,                   # 12.28添加
    "classifications": [],          # 12.28
    "images": [],
    "topics": [],
    "covers": [],
    "videos": [],
    "audios": [],
    "readNum": 0,
    "likeNum": 0,
    "commentNum": 0,
    "forwardNum": 0,
    "collectNum": 0,
    "wxLookNum": 0,
    "wangYiJoinNum": 0,
    "updateParams": "",
    "sentiment": -1,
    "sentimentPositiveProb": -1,
    "sentimentRawInfo": "",
    "tags": [],
    "tagsLength": 0,
    "personNames": [],
    "regionNames": [],
    "organizationNames": [],
    "keywords": [],
    "segmentWordsRawInfo": [],
    "wordFrequency": [],
    "wordFrequencyLength": 0,
    "hasDiscovery": -1,
    "hasSpread": -1,
    "hasSimilarWorks": -1,
    "hasSimilarOriginalWorks": -1,
    "reprintNum": 0,
    "reprintMediaNum": 0,
    "HI": 0.0,                      # 2021.1.11日添加
    "spreadHI": 0.0,
    "interactiveHI": 0.0,
    "spreadHIIncreasement": 0.0,    # 2021.1.16日albert添加
    "pubTime": 0,
    "createTime": 0,
    "updateTime": 0,
}


DEFAULT_FORUM_FIELDS = {
    "status": 1,
    "platformID": "",
    "platformName": "",
    "sourceTypesName": "论坛",
    "name": "",
    "forumId": "",
    "introduction": "",
    "logo": "",
    "url": "",
    "region": "",
    "type": 6,
    "parentID": "",
    "parentName": "",
    "levelNumber": -1,
    "followsNum": 0,
    "worksNum": 0,
    "createTime": 0,
    "updateTime": 0,
}


DEFAULT_FORUM_DETAILS_FIELDS = {
    "status": 1,
    "sourceTypesName": "论坛",
    "platformWorksID": "",
    "platformID": "",
    "platformName": "",
    "platformType": 6,
    "parentID": "",
    "parentName": "",
    "accountID": "",
    "accountUrl": "",
    "accountName": "",
    "url": "",
    "authors": [],
    "title": "",
    "titleWordsNum": 0,
    "content": "",
    "contentWordsNum": 0,
    "question": "",
    "oneAnswer": "",
    "answer": "",
    "html": "",
    "simhash": "",
    "contentType": -1,
    "digest": "",
    "digestOriginal": "",
    "digestCompute": "",
    "source": "",
    "isOriginal": -1,
    "isOriginalCompute": -1,
    "isTop": -1,
    "isPush": -1,
    "classifications": [],
    "images": [],
    "topics": [],
    "covers": [],
    "videos": [],
    "audios": [],
    "readNum": 0,
    "likeNum": 0,
    "commentNum": 0,
    "forwardNum": 0,
    "collectNum": 0,
    "updateParams": "",
    "sentiment": -1,
    "sentimentPositiveProb": -1,
    "sentimentRawInfo": "",
    "tags": [],
    "tagsLength": 0,
    "personNames": [],
    "regionNames": [],
    "organizationNames": [],
    "keywords": [],
    "segmentWordsRawInfo": [],
    "wordFrequency": [],
    "wordFrequencyLength": 0,
    "hasDiscovery": -1,
    "hasSpread": -1,
    "hasSimilarWorks": -1,
    "hasSimilarOriginalWorks": -1,
    "reprintNum": 0,
    "reprintMediaNum": 0,
    "spreadHI": 0,
    "interactiveHI": 0,
    "spreadHIIncreasement": 0.0,  # 2021.1.16日albert添加
    "pubTime": 0,
    "createTime": 0,
    "updateTime": 0,
}


